export const frasesList = [
    { id: 1, frase: "No puedes controlar el viento, pero sí puedes ajustar las velas", isFavorite: false, isExcluded: false },
    { id: 2, frase: "Al final, solo lamentamos lo que no hemos hecho", isFavorite: false, isExcluded: false },
    { id: 3, frase: "If I died tomorrow I would never regret", isFavorite: false, isExcluded: false },
    { id: 4, frase: "Siempre hay que elegir un bando aunque sea el equivocado", isFavorite: false, isExcluded: false },
    { id: 5, frase: "És difícil vèncer una persona que mai es rendeix", isFavorite: false, isExcluded: false },
    { id: 6, frase: "Hope the best and prepare for the worst", isFavorite: false, isExcluded: false },
    { id: 7, frase: "Será una locura si sale mal. Pero será una buena historia si funciona", isFavorite: false, isExcluded: false },
    { id: 8, frase: "El mal geni ens fot en embolics. L'orgull el que ens manté en ells", isFavorite: false, isExcluded: false },
    { id: 9, frase: "Do remember they can't cancel the spring", isFavorite: false, isExcluded: false },
    { id: 10, frase: "El éxito no es el final, el fracaso no es fatal: lo que cuenta es el coraje para continuar.", isFavorite: false, isExcluded: false },
    { id: 11, frase: "La vida es 10% lo que te ocurre y 90% cómo reaccionas a ello.", isFavorite: false, isExcluded: false },
    { id: 12, frase: "No es la altura, ni el peso, ni los músculos, es la constancia lo que te hace triunfar.", isFavorite: false, isExcluded: false },
    { id: 13, frase: "La perfección no es alcanzable, pero si perseguimos la perfección podemos alcanzar la excelencia.", isFavorite: false, isExcluded: false },
    { id: 14, frase: "El único modo de hacer un gran trabajo es amar lo que haces.", isFavorite: false, isExcluded: false },
    { id: 15, frase: "Cada día es una nueva oportunidad para cambiar tu vida.", isFavorite: false, isExcluded: false },
    { id: 16, frase: "El verdadero fracaso no es intentar y fallar, sino no intentarlo en absoluto.", isFavorite: false, isExcluded: false },
    { id: 17, frase: "El único lugar donde el éxito viene antes del trabajo es en el diccionario.", isFavorite: false, isExcluded: false },
    { id: 18, frase: "La disciplina es el puente entre tus metas y tus logros.", isFavorite: false, isExcluded: false },
    { id: 19, frase: "No cuentes los días, haz que los días cuenten.", isFavorite: false, isExcluded: false },
    { id: 20, frase: "Las personas que están lo suficientemente locas como para pensar que pueden cambiar el mundo son las que lo hacen.", isFavorite: false, isExcluded: false },
];
